[package]
name = "stylus-erc721"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
alloy-primitives = "=0.8.20"
alloy-sol-types = "=0.8.20"
dotenv = "0.15.0"
hex = "0.4.3"
mini-alloc = "0.9.0"
stylus-sdk = "0.9.0"

[dev-dependencies]
tokio = { version = "1.12.0", features = ["full"] }
ethers = "2.0"
eyre = "0.6.8"
stylus-sdk = { version = "0.9.0", features = ["stylus-test"] }

[features]
export-abi = ["stylus-sdk/export-abi"]
debug = ["stylus-sdk/debug"]

[[bin]]
name = "stylus-erc721"
path = "src/main.rs"

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"

opt-level = 3
